1.

In [29]:
import numpy as np

print("NumPy version:", np.__version__)
np.show_config()


NumPy version: 2.3.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-vuy4otnh/cp312-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-vuy4otnh/cp312-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.30  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Haswell MAX_THREADS=24
    pc file directory: D:/a/numpy-release/numpy-release/.openblas
    version: 0.3.30
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-vuy4otnh/cp312-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-vuy4otnh/cp312-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openbl

2.

In [30]:
import numpy as np

# 1. Tạo array từ 0–9
arr = np.arange(10)
print(arr)
print("dtype:", arr.dtype)
print("shape:", arr.shape)

# 2. Tạo arr_odd và arr_even
arr_odd = arr[arr % 2 == 1]
arr_even = arr[arr % 2 == 0]

print("Odd:", arr_odd)
print("Even:", arr_even)

# 3. Thay số lẻ bằng 100
arr_update_1 = arr.copy()
arr_update_1[arr_update_1 % 2 == 1] = 100
print(arr_update_1)


[0 1 2 3 4 5 6 7 8 9]
dtype: int64
shape: (10,)
Odd: [1 3 5 7 9]
Even: [0 2 4 6 8]
[  0 100   2 100   4 100   6 100   8 100]


3.

In [31]:
import numpy as np

arr_a = np.array([1,2,3,2,3,4,3,4,5,6])
arr_b = np.array([7,2,10,2,7,4,9,4,9,8])

# 1. Phần tử xuất hiện ở cả arr_a và arr_b
arr_c = np.intersect1d(arr_a, arr_b)
print(arr_c)

# 2. Phần tử chỉ có ở arr_a
arr_d = np.setdiff1d(arr_a, arr_b)
print(arr_d)

# 3. Lọc giá trị từ 5 đến 10
arr_e = np.array([2,6,1,9,10,3,27,8,6,25,16])
arr_f = arr_e[(arr_e >= 5) & (arr_e <= 10)]
print(arr_f)


[2 4]
[1 3 5 6]
[ 6  9 10  8  6]


4.

In [32]:
import numpy as np

# 1
arr_zeros = np.zeros(10, dtype=int)
arr_zeros[5] = 1
print(arr_zeros)

# 2
arr_h = np.arange(10, 25)
print(arr_h[::-1])

# 3
arr_k = np.array([1,2,0,8,2,0,1,3,0,5,0])
arr_l = arr_k[arr_k != 0]
print(arr_l)

# 4
arr_l = np.append(arr_l, [10, 20])
print(arr_l)

# 5
arr_l = np.insert(arr_l, 5, 100)
print(arr_l)

# 6
arr_l = np.delete(arr_l, [0,1,2])
print(arr_l)


[0 0 0 0 0 1 0 0 0 0]
[24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]
[1 2 8 2 1 3 5]
[ 1  2  8  2  1  3  5 10 20]
[  1   2   8   2   1 100   3   5  10  20]
[  2   1 100   3   5  10  20]


5.

In [33]:
import numpy as np

# đọc dữ liệu từ file txt
height = np.loadtxt("heights_1.txt")
weight = np.loadtxt("weights_1.txt")

# tạo numpy array
arr_height = np.array(height)
arr_weight = np.array(weight)

# đổi đơn vị
arr_height_m = arr_height * 0.0254
arr_weight_kg = arr_weight * 0.453592

# BMI
arr_bmi = arr_weight_kg / (arr_height_m ** 2)

print(arr_height_m[:5])
print(arr_weight_kg[:5])
print(arr_bmi[:5])


[1.8796 1.8796 1.8288 1.8288 1.8542]
[81.64656  97.52228  95.25432  95.25432  85.275296]
[23.11037639 27.60406069 28.48080465 28.48080465 24.80333518]


6.

In [34]:
import numpy as np

# 1
arr = np.ones((3,3), dtype=bool)

# 2
arr_1D = np.array([0,1,2,3,4,5,6,7,8])
arr_2D = arr_1D.reshape(3,3)
arr_2D[:, [0,2]] = arr_2D[:, [2,0]]

# 3
arr_2D[[0,1]] = arr_2D[[1,0]]

# 4
arr_2D = arr_2D[::-1]

# 5
arr_2D = arr_2D[:, ::-1]

# 6
arr_2D_null = np.array([[1,2,3],[np.nan,5,6],[7,np.nan,9],[4,5,6]])
print(np.isnan(arr_2D_null).any())

# 7
arr_2D_null[np.isnan(arr_2D_null)] = 0
print(arr_2D_null)


True
[[1. 2. 3.]
 [0. 5. 6.]
 [7. 0. 9.]
 [4. 5. 6.]]


7.

In [35]:
import numpy as np

# build the baseball dataset from existing height and weight arrays if available
try:
	baseball = list(zip(height, weight))
except NameError:
	# fallback to empty list if height/weight are not defined
	baseball = []

np_baseball = np.array(baseball)

print("shape:", np_baseball.shape)
print("dtype:", np_baseball.dtype)

# safe access for row 49
if np_baseball.shape[0] > 49:
	print(np_baseball[49])
else:
	print(f"Row 49 not available (only {np_baseball.shape[0]} rows)")

# extract weight column if present
if np_baseball.ndim == 2 and np_baseball.shape[1] > 1:
	np_weight = np_baseball[:, 1].astype(float)
else:
	np_weight = np.array([])

# safe access for row 123, column 0
if np_baseball.shape[0] > 123:
	print(np_baseball[123, 0])
elif np_baseball.shape[0] > 0:
	print("Row 123 not available; showing last row first column:", np_baseball[-1, 0])
else:
	print("np_baseball is empty")

# compute means if possible
if np_baseball.ndim == 2 and np_baseball.shape[1] > 0:
	print("mean first column:", np_baseball[:, 0].astype(float).mean())
else:
	print("No valid first column to compute mean")

if np_weight.size > 0:
	print("mean weight column:", np_weight.mean())
else:
	print("No weight column to compute mean")


shape: (20, 2)
dtype: float64
Row 49 not available (only 20 rows)
Row 123 not available; showing last row first column: 74.0
mean first column: 72.1
mean weight column: 197.35


8.

In [36]:
import numpy as np

positions = np.loadtxt("positions.txt", dtype=str)
heights = np.loadtxt("heights.txt")

np_positions = np.array(positions)
np_heights = np.array(heights)


9.

In [37]:
import pandas as pd

euro12 = pd.read_csv("euro2012.csv")

print(euro12['Goals'])
print(euro12.shape)
print(euro12.info())

discipline = euro12[['Team','Yellow Cards','Red Cards']]
discipline.sort_values(['Red Cards','Yellow Cards'], ascending=False)

print(euro12['Yellow Cards'].mean())
print(euro12[euro12.Goals > 6])
print(euro12[euro12.Team.str.startswith('G')])
print(euro12.iloc[:, :-3])


0    12
1     6
2    10
3     6
4     3
5     5
6     5
7     5
Name: Goals, dtype: int64
(8, 6)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   Team              8 non-null      object
 1   Goals             8 non-null      int64 
 2   Shots on target   8 non-null      int64 
 3   Shots off target  8 non-null      int64 
 4   Yellow Cards      8 non-null      int64 
 5   Red Cards         8 non-null      int64 
dtypes: int64(5), object(1)
memory usage: 516.0+ bytes
None
9.375
      Team  Goals  Shots on target  Shots off target  Yellow Cards  Red Cards
0    Spain     12               42                33            11          0
2  Germany     10               32                32            10          1
      Team  Goals  Shots on target  Shots off target  Yellow Cards  Red Cards
2  Germany     10               32                32     

10.

In [38]:
import pandas as pd

drink = pd.read_csv("drinks.csv", index_col=0)

print(drink.groupby('continent')['beer_servings'].mean())
print(drink.groupby('continent').wine_servings.describe())
print(drink.groupby('continent').median())
print(drink.groupby('continent')['spirit_servings'].agg(['mean','max','min']))

drink.sort_values('beer_servings', ascending=False).head()
drink.sort_values('beer_servings').head()


continent
Africa           121.0
Asia               0.0
Europe           167.0
Oceania          261.0
South America    193.0
Name: beer_servings, dtype: float64
               count   mean        std    min     25%    50%     75%    max
continent                                                                  
Africa           2.0   29.5   21.92031   14.0   21.75   29.5   37.25   45.0
Asia             1.0    0.0        NaN    0.0    0.00    0.0    0.00    0.0
Europe           2.0  183.0  182.43355   54.0  118.50  183.0  247.50  312.0
Oceania          1.0  212.0        NaN  212.0  212.00  212.0  212.00  212.0
South America    1.0  221.0        NaN  221.0  221.00  221.0  221.00  221.0
               beer_servings  spirit_servings  wine_servings  \
continent                                                      
Africa                 121.0             28.5           29.5   
Asia                     0.0              0.0            0.0   
Europe                 167.0            135.0      

beer_servings  spirit_servings  wine_servings  \
country                                                      
Afghanistan              0                0              0   
Algeria                 25                0             14   
Albania                 89              132             54   
Argentina              193               25            221   
Angola                 217               57             45   

             total_litres_of_pure_alcohol      continent  
country                                                   
Afghanistan                           0.0           Asia  
Algeria                               0.7         Africa  
Albania                               4.9         Europe  
Argentina                             8.3  South America  
Angola                                5.9         Africa

11.

In [39]:
import pandas as pd

stocks1 = pd.read_csv("stocks1.csv")
stocks2 = pd.read_csv("stocks2.csv")
companies = pd.read_csv("companies.csv")

stocks = pd.concat([stocks1, stocks2])
stocks_companies = stocks.merge(companies, on='symbol')

stocks_companies['parsed_time'] = pd.to_datetime(stocks_companies['date'])
stocks_companies['result'] = stocks_companies.apply(
    lambda x: 'up' if x.close > x.open else 'down', axis=1)


12.

In [40]:
import pandas as pd
import numpy as np


In [41]:
movies = pd.read_csv("movies.csv")
ratings = pd.read_csv("ratings.csv")
tags = pd.read_csv("tags.csv")
links = pd.read_csv("links.csv")


In [42]:
movies.isnull().sum()
ratings.isnull().sum()
tags.isnull().sum()
links.isnull().sum()


movieId    0
imdbId     0
tmdbId     0
dtype: int64

In [43]:
tags = tags.dropna()


In [44]:
ratings['datetime'] = pd.to_datetime(ratings['timestamp'], unit='s')
tags['datetime'] = pd.to_datetime(tags['timestamp'], unit='s')


In [45]:
ratings[['timestamp','datetime']].head()


timestamp            datetime
0  964982703 2000-07-30 18:45:03
1  964981247 2000-07-30 18:20:47
2  964982224 2000-07-30 18:37:04
3  964982931 2000-07-30 18:48:51
4  964983815 2000-07-30 19:03:35

In [46]:
movie_ratings = pd.merge(ratings, movies, on='movieId')
movie_ratings.head()


userId  movieId  rating  timestamp            datetime  \
0       1        1     4.0  964982703 2000-07-30 18:45:03   
1       1        3     4.0  964981247 2000-07-30 18:20:47   
2       2        1     5.0  964982224 2000-07-30 18:37:04   
3       2        2     3.0  964982931 2000-07-30 18:48:51   
4       3        4     2.0  964983815 2000-07-30 19:03:35   

                      title                                       genres  
0          Toy Story (1995)  Adventure|Animation|Children|Comedy|Fantasy  
1   Grumpier Old Men (1995)                               Comedy|Romance  
2          Toy Story (1995)  Adventure|Animation|Children|Comedy|Fantasy  
3            Jumanji (1995)                   Adventure|Children|Fantasy  
4  Waiting to Exhale (1995)                                 Comedy|Drama

In [47]:
movie_full = pd.merge(movie_ratings, tags, on=['movieId','userId'], how='left')
movie_full.head()


userId  movieId  rating  timestamp_x          datetime_x  \
0       1        1     4.0    964982703 2000-07-30 18:45:03   
1       1        3     4.0    964981247 2000-07-30 18:20:47   
2       2        1     5.0    964982224 2000-07-30 18:37:04   
3       2        2     3.0    964982931 2000-07-30 18:48:51   
4       3        4     2.0    964983815 2000-07-30 19:03:35   

                      title                                       genres  \
0          Toy Story (1995)  Adventure|Animation|Children|Comedy|Fantasy   
1   Grumpier Old Men (1995)                               Comedy|Romance   
2          Toy Story (1995)  Adventure|Animation|Children|Comedy|Fantasy   
3            Jumanji (1995)                   Adventure|Children|Fantasy   
4  Waiting to Exhale (1995)                                 Comedy|Drama   

        tag  timestamp_y          datetime_y  
0     funny  964982703.0 2000-07-30 18:45:03  
1       NaN          NaN                 NaT  
2       NaN          NaN                 NaT  
3   fantasy  964982931.0 2000-07-30 18:48:51  
4  romantic  964983815.0 2000-07-30 19:03:35

In [48]:
movies['movieId'].nunique()


4

In [49]:
ratings['userId'].nunique()


3

In [50]:
ratings['rating'].mean()


np.float64(3.6)

In [51]:
ratings.groupby('movieId').size().sort_values(ascending=False).head()


movieId
1    2
2    1
3    1
4    1
dtype: int64

In [52]:
avg_rating = ratings.groupby('movieId')['rating'].mean()
high_rating_movies = avg_rating[avg_rating >= 4]

high_rating_movies.head()


movieId
1    4.5
3    4.0
Name: rating, dtype: float64

In [53]:
high_rating_movies = high_rating_movies.reset_index()
high_rating_movies = pd.merge(high_rating_movies, movies, on='movieId')
high_rating_movies[['title','rating']].head()


title  rating
0         Toy Story (1995)     4.5
1  Grumpier Old Men (1995)     4.0

In [54]:
movies_genres = movies.copy()
movies_genres['genres'] = movies_genres['genres'].str.split('|')


In [55]:
movies_genres = movies_genres.explode('genres')
movies_genres.head()


movieId             title     genres
0        1  Toy Story (1995)  Adventure
0        1  Toy Story (1995)  Animation
0        1  Toy Story (1995)   Children
0        1  Toy Story (1995)     Comedy
0        1  Toy Story (1995)    Fantasy

In [56]:
movies_genres['genres'].value_counts()


genres
Comedy       3
Children     2
Adventure    2
Fantasy      2
Animation    1
Romance      1
Drama        1
Name: count, dtype: int64

In [57]:
genre_rating = pd.merge(movies_genres, ratings, on='movieId')

genre_rating.groupby('genres')['rating'].mean().sort_values(ascending=False)


genres
Animation    4.50
Adventure    4.00
Children     4.00
Romance      4.00
Fantasy      4.00
Comedy       3.75
Drama        2.00
Name: rating, dtype: float64

In [58]:
ratings['year'] = ratings['datetime'].dt.year

ratings.groupby('year')['rating'].mean()


year
2000    3.6
Name: rating, dtype: float64

In [59]:
import pandas as pd

df = pd.read_csv("euro2012.csv")
print(df.head())


       Team  Goals  Shots on target  Shots off target  Yellow Cards  Red Cards
0     Spain     12               42                33            11          0
1     Italy      6               34                45            16          0
2   Germany     10               32                32            10          1
3  Portugal      6               22                42            12          0
4    France      3               22                24             6          0
